### YamlMime:ManagedReference
items:
- uid: System.Transactions.TransactionInDoubtException
  id: TransactionInDoubtException
  children:
  - System.Transactions.TransactionInDoubtException.#ctor
  - System.Transactions.TransactionInDoubtException.#ctor(System.String)
  - System.Transactions.TransactionInDoubtException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Transactions.TransactionInDoubtException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: TransactionInDoubtException
  nameWithType: TransactionInDoubtException
  fullName: System.Transactions.TransactionInDoubtException
  type: Class
  summary: "对处于不确定的事务尝试操作，或尝试提交事务，事务时引发的异常将成为 InDoubt。"
  remarks: "当尝试对状态不明的事务进行的操作时，引发此异常。 当无法确定事务的状态，事务将处于不确定。 具体而言，事务，最终结果是提交还是中止，永远是未知的此事务。       当尝试提交事务并事务成为 InDoubt，也会引发此异常。       这是可恢复错误。"
  syntax:
    content: 'public class TransactionInDoubtException : System.Transactions.TransactionException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Transactions.TransactionException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Transactions.TransactionInDoubtException.#ctor
  id: '#ctor'
  parent: System.Transactions.TransactionInDoubtException
  langs:
  - csharp
  name: TransactionInDoubtException()
  nameWithType: TransactionInDoubtException.TransactionInDoubtException()
  fullName: System.Transactions.TransactionInDoubtException.TransactionInDoubtException()
  type: Constructor
  assemblies:
  - System.Transactions
  namespace: System.Transactions
  summary: "初始化的新实例<xref href=&quot;System.Transactions.TransactionInDoubtException&quot;></xref>类。"
  syntax:
    content: public TransactionInDoubtException ();
    parameters: []
  overload: System.Transactions.TransactionInDoubtException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Transactions.TransactionInDoubtException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Transactions.TransactionInDoubtException
  langs:
  - csharp
  name: TransactionInDoubtException(String)
  nameWithType: TransactionInDoubtException.TransactionInDoubtException(String)
  fullName: System.Transactions.TransactionInDoubtException.TransactionInDoubtException(String)
  type: Constructor
  assemblies:
  - System.Transactions
  namespace: System.Transactions
  summary: "初始化的新实例<xref href=&quot;System.Transactions.TransactionInDoubtException&quot;></xref>使用指定的消息的类。"
  syntax:
    content: public TransactionInDoubtException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A <xref:System.String>，其中包含一条消息，说明发生异常的原因。</xref:System.String>"
  overload: System.Transactions.TransactionInDoubtException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Transactions.TransactionInDoubtException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Transactions.TransactionInDoubtException
  langs:
  - csharp
  name: TransactionInDoubtException(SerializationInfo,StreamingContext)
  nameWithType: TransactionInDoubtException.TransactionInDoubtException(SerializationInfo,StreamingContext)
  fullName: System.Transactions.TransactionInDoubtException.TransactionInDoubtException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Transactions
  namespace: System.Transactions
  summary: "初始化的新实例<xref href=&quot;System.Transactions.TransactionInDoubtException&quot;></xref>类，该类具有指定的序列化和流式处理上下文信息。"
  syntax:
    content: protected TransactionInDoubtException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "A <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref>描述失败的序列化的对象。"
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "A <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref>描述失败的序列化上下文的对象。"
  overload: System.Transactions.TransactionInDoubtException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Transactions.TransactionInDoubtException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Transactions.TransactionInDoubtException
  langs:
  - csharp
  name: TransactionInDoubtException(String,Exception)
  nameWithType: TransactionInDoubtException.TransactionInDoubtException(String,Exception)
  fullName: System.Transactions.TransactionInDoubtException.TransactionInDoubtException(String,Exception)
  type: Constructor
  assemblies:
  - System.Transactions
  namespace: System.Transactions
  summary: "初始化的新实例<xref href=&quot;System.Transactions.TransactionInDoubtException&quot;></xref>使用指定的消息和内部异常的类。"
  syntax:
    content: public TransactionInDoubtException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A <xref:System.String>，其中包含一条消息，说明发生异常的原因。</xref:System.String>"
    - id: innerException
      type: System.Exception
      description: "获取导致当前异常的异常实例。 有关详细信息，请参阅<xref:System.Exception.InnerException*>属性。</xref:System.Exception.InnerException*>"
  overload: System.Transactions.TransactionInDoubtException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Transactions.TransactionException
  isExternal: false
  name: System.Transactions.TransactionException
- uid: System.Transactions.TransactionInDoubtException.#ctor
  parent: System.Transactions.TransactionInDoubtException
  isExternal: false
  name: TransactionInDoubtException()
  nameWithType: TransactionInDoubtException.TransactionInDoubtException()
  fullName: System.Transactions.TransactionInDoubtException.TransactionInDoubtException()
- uid: System.Transactions.TransactionInDoubtException.#ctor(System.String)
  parent: System.Transactions.TransactionInDoubtException
  isExternal: false
  name: TransactionInDoubtException(String)
  nameWithType: TransactionInDoubtException.TransactionInDoubtException(String)
  fullName: System.Transactions.TransactionInDoubtException.TransactionInDoubtException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Transactions.TransactionInDoubtException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Transactions.TransactionInDoubtException
  isExternal: false
  name: TransactionInDoubtException(SerializationInfo,StreamingContext)
  nameWithType: TransactionInDoubtException.TransactionInDoubtException(SerializationInfo,StreamingContext)
  fullName: System.Transactions.TransactionInDoubtException.TransactionInDoubtException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Transactions.TransactionInDoubtException.#ctor(System.String,System.Exception)
  parent: System.Transactions.TransactionInDoubtException
  isExternal: false
  name: TransactionInDoubtException(String,Exception)
  nameWithType: TransactionInDoubtException.TransactionInDoubtException(String,Exception)
  fullName: System.Transactions.TransactionInDoubtException.TransactionInDoubtException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Transactions.TransactionInDoubtException.#ctor*
  parent: System.Transactions.TransactionInDoubtException
  isExternal: false
  name: TransactionInDoubtException
  nameWithType: TransactionInDoubtException.TransactionInDoubtException
