### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Services.AsynchronousOperationException
  id: AsynchronousOperationException
  children:
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Exception)
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String)
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: AsynchronousOperationException
  nameWithType: AsynchronousOperationException
  fullName: System.IdentityModel.Services.AsynchronousOperationException
  type: Class
  summary: "异步操作期间发生错误时引发的异常。"
  syntax:
    content: 'public class AsynchronousOperationException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException()
  nameWithType: AsynchronousOperationException.AsynchronousOperationException()
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException()
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "初始化的新实例<xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;></xref>类。"
  remarks: "此构造函数初始化<xref:SystemException.Message>属性为系统提供的消息的描述错误的新实例。</xref:SystemException.Message> 此消息将当前系统区域性考虑在内。       下表显示新实例的初始属性的值。      |属性 |值 |  |--------------|-----------|  |<xref:System.Exception.InnerException>|`null`.|  |<xref:System.Exception.Message>|本地化的错误消息字符串。 |</xref:System.Exception.Message> </xref:System.Exception.InnerException>"
  syntax:
    content: public AsynchronousOperationException ();
    parameters: []
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Exception)
  id: '#ctor(System.Exception)'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(Exception)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(Exception)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "初始化的新实例<xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;></xref>使用系统提供的错误消息和对导致此异常的内部异常的引用的类。"
  remarks: "前一个异常的直接结果应包含中的前一个异常的引用引发的异常，<xref:System.Exception.InnerException>属性。</xref:System.Exception.InnerException> <xref:System.Exception.InnerException>属性返回传递到构造函数的相同值。</xref:System.Exception.InnerException>       下表显示新实例的初始属性的值。      |属性 |值 |  |--------------|-----------|  |<xref:System.Exception.InnerException>|内部异常引用。 |  |<xref:System.Exception.Message>|描述错误的系统提供的消息。</xref:System.Exception.Message> </xref:System.Exception.InnerException> 此消息当前系统区域性考虑在内。 |"
  syntax:
    content: public AsynchronousOperationException (Exception innerException);
    parameters:
    - id: innerException
      type: System.Exception
      description: "<xref:System.Exception>导致当前异常。</xref:System.Exception> 如果`innerException`参数不是<xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>中, 引发当前异常<xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;></xref>处理内部异常的块。"
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(String)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(String)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "初始化的新实例<xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;></xref>与指定的错误消息的类。"
  remarks: "此构造函数初始化<xref:System.Exception.Message>属性的新异常使用`message`参数。</xref:System.Exception.Message> 内容`message`旨在为人所理解。 此构造函数的调用方需要确保此字符串已针对当前系统区域性进行了本地化。       下表显示新实例的初始属性的值。      |属性 |值 |  |--------------|-----------|  |<xref:System.Exception.InnerException>|`null`.|  |<xref:System.Exception.Message>|错误消息字符串。 |</xref:System.Exception.Message> </xref:System.Exception.InnerException>"
  syntax:
    content: public AsynchronousOperationException (string message);
    parameters:
    - id: message
      type: System.String
      description: "解释异常原因的错误消息。"
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(SerializationInfo,StreamingContext)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "初始化的新实例<xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;></xref>用序列化数据的类。"
  remarks: "在反序列化，以便重建通过流传输的异常对象过程中调用此构造函数。"
  syntax:
    content: protected AsynchronousOperationException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "A <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref>保存的序列化的对象数据的对象。"
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "A<xref:System.Runtime.Serialization.StreamingContext>对象，其中包含有关源或目标的上下文信息。</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(String,Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String,Exception)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(String,Exception)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "初始化的新实例<xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;></xref>使用指定的错误消息和对导致此异常的内部异常的引用的类。"
  remarks: "前一个异常的直接结果应包含中的前一个异常的引用引发的异常，<xref:System.Exception.InnerException>属性。</xref:System.Exception.InnerException> <xref:System.Exception.InnerException>属性返回传递到构造函数的相同值。</xref:System.Exception.InnerException>       下表显示新实例的初始属性的值。      |属性 |值 |  |--------------|-----------|  |<xref:System.Exception.InnerException>|内部异常引用。 |  |<xref:System.Exception.Message>|错误消息字符串。 |</xref:System.Exception.Message> </xref:System.Exception.InnerException>"
  syntax:
    content: public AsynchronousOperationException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "解释异常原因的错误消息。"
    - id: innerException
      type: System.Exception
      description: "<xref:System.Exception>导致当前异常。</xref:System.Exception> 如果`innerException`参数不是<xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>中, 引发当前异常<xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;></xref>处理内部异常的块。"
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException()
  nameWithType: AsynchronousOperationException.AsynchronousOperationException()
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException()
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Exception)
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(Exception)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(Exception)
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String)
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(String)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(SerializationInfo,StreamingContext)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String,System.Exception)
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(String,Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String,Exception)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(String,Exception)
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException
  nameWithType: AsynchronousOperationException.AsynchronousOperationException
