### YamlMime:ManagedReference
items:
- uid: System.Runtime.Remoting.RemotingTimeoutException
  id: RemotingTimeoutException
  children:
  - System.Runtime.Remoting.RemotingTimeoutException.#ctor
  - System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)
  - System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: RemotingTimeoutException
  nameWithType: RemotingTimeoutException
  fullName: System.Runtime.Remoting.RemotingTimeoutException
  type: Class
  summary: "以前指定的时间段无法到达服务器或客户端时，将引发异常。"
  remarks: "在指定的超时时间内未完成的远程处理调用时，将引发 RemotingTimeoutException。       RemotingTimeoutException 使用 HRESULT COR_E_REMOTING，其值 0x8013150B。       RemotingTimeoutException 使用默认<xref:System.Object.Equals%2A>实现，它支持引用相等性。</xref:System.Object.Equals%2A>       RemotingTimeoutException 的实例的初始属性值的列表，请参阅 RemotingTimeoutException 构造函数。"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class RemotingTimeoutException : System.Runtime.Remoting.RemotingException
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Runtime.Remoting.RemotingException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor
  id: '#ctor'
  parent: System.Runtime.Remoting.RemotingTimeoutException
  langs:
  - csharp
  name: RemotingTimeoutException()
  nameWithType: RemotingTimeoutException.RemotingTimeoutException()
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "初始化的新实例<xref href=&quot;System.Runtime.Remoting.RemotingTimeoutException&quot;></xref>使用默认属性的类。"
  remarks: "<xref:System.Runtime.Remoting.RemotingTimeoutException>继承<xref:System.Exception>类。</xref:System.Exception></xref:System.Runtime.Remoting.RemotingTimeoutException> 下表显示<xref:System.Runtime.Remoting.RemotingTimeoutException>类的实例的初始属性值: |属性 |值 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|`null`|  |<xref:System.Exception.Message%2A>|本地化的错误消息以<xref:System.Runtime.Remoting.RemotingTimeoutException>|</xref:System.Runtime.Remoting.RemotingTimeoutException> </xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingTimeoutException>"
  syntax:
    content: public RemotingTimeoutException ();
    parameters: []
  overload: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Runtime.Remoting.RemotingTimeoutException
  langs:
  - csharp
  name: RemotingTimeoutException(String)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "初始化的新实例<xref href=&quot;System.Runtime.Remoting.RemotingTimeoutException&quot;></xref>使用指定的消息的类。"
  remarks: "<xref:System.Runtime.Remoting.RemotingTimeoutException>继承<xref:System.Exception>类。</xref:System.Exception></xref:System.Runtime.Remoting.RemotingTimeoutException> 下表显示<xref:System.Runtime.Remoting.RemotingTimeoutException>类的实例的初始属性值: |属性类型 |条件 |  |-------------------|---------------|  |<xref:System.Exception.InnerException%2A>|`null`|  |<xref:System.Exception.Message%2A>|`message`字符串 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingTimeoutException>"
  syntax:
    content: public RemotingTimeoutException (string message);
    parameters:
    - id: message
      type: System.String
      description: "指示发生异常的原因的消息。"
  overload: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Runtime.Remoting.RemotingTimeoutException
  langs:
  - csharp
  name: RemotingTimeoutException(String,Exception)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String,Exception)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "初始化的新实例<xref href=&quot;System.Runtime.Remoting.RemotingTimeoutException&quot;></xref>使用指定的错误消息和对导致此异常的内部异常的引用的类。"
  remarks: "前一个异常的直接结果必须包含的引用中的前一个异常引发的异常，<xref:System.Exception.InnerException%2A>属性。</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>属性返回相同的值传递到构造函数中，或`null`如果<xref:System.Exception.InnerException%2A>属性不会提供给构造函数的内部异常值。</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       下表显示<xref:System.Runtime.Remoting.RemotingTimeoutException>类的实例的初始属性值: |属性 |值 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|内部异常引用 |  |<xref:System.Exception.Message%2A>|错误消息字符串 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingTimeoutException>"
  syntax:
    content: public RemotingTimeoutException (string message, Exception InnerException);
    parameters:
    - id: message
      type: System.String
      description: "解释异常原因的错误消息。"
    - id: InnerException
      type: System.Exception
      description: "导致当前异常的异常。 如果`InnerException`参数不是<xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>中, 引发当前异常<xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;></xref>处理内部异常的块。"
  overload: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Runtime.Remoting.RemotingException
  isExternal: false
  name: System.Runtime.Remoting.RemotingException
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException()
  nameWithType: RemotingTimeoutException.RemotingTimeoutException()
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException()
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException(String)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException(String,Exception)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String,Exception)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException
  nameWithType: RemotingTimeoutException.RemotingTimeoutException
