### YamlMime:ManagedReference
items:
- uid: System.NotFiniteNumberException
  id: NotFiniteNumberException
  children:
  - System.NotFiniteNumberException.#ctor
  - System.NotFiniteNumberException.#ctor(System.Double)
  - System.NotFiniteNumberException.#ctor(System.String)
  - System.NotFiniteNumberException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.NotFiniteNumberException.#ctor(System.String,System.Double)
  - System.NotFiniteNumberException.#ctor(System.String,System.Exception)
  - System.NotFiniteNumberException.#ctor(System.String,System.Double,System.Exception)
  - System.NotFiniteNumberException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.NotFiniteNumberException.OffendingNumber
  langs:
  - csharp
  name: NotFiniteNumberException
  nameWithType: NotFiniteNumberException
  fullName: System.NotFiniteNumberException
  type: Class
  summary: "在浮点值为正无穷大、 负无穷大或非数值 (NaN) 时引发的异常。"
  remarks: "NotFiniteNumberException 是针对在浮点操作中不支持的无穷大和非数字概念的编程语言提供。       NotFiniteNumberException 使用 HRESULT COR_E_NOTFINITENUMBER，其值 0x80131528。       NotFiniteNumberException 的实例的初始属性值的列表，请参阅<xref:System.NotFiniteNumberException.%23ctor%2A>构造函数。</xref:System.NotFiniteNumberException.%23ctor%2A>"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class NotFiniteNumberException : ArithmeticException
  inheritance:
  - System.ArithmeticException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.NotFiniteNumberException.#ctor
  id: '#ctor'
  parent: System.NotFiniteNumberException
  langs:
  - csharp
  name: NotFiniteNumberException()
  nameWithType: NotFiniteNumberException.NotFiniteNumberException()
  fullName: System.NotFiniteNumberException.NotFiniteNumberException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "初始化的新实例<xref href=&quot;System.NotFiniteNumberException&quot;></xref>类。"
  remarks: "此构造函数初始化<xref:System.Exception.Message%2A>为系统提供的消息描述该错误，如&quot;遇到号已不是有限的数量。&quot;的新实例的属性</xref:System.Exception.Message%2A> 此消息将当前系统区域性考虑在内。       下表显示<xref:System.NotFiniteNumberException>.</xref:System.NotFiniteNumberException>实例的初始属性的值      |属性 |值 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|空引用 (`Nothing`在 Visual Basic 中)。 |  |<xref:System.Exception.Message%2A>|本地化的错误消息字符串。 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public NotFiniteNumberException ();
    parameters: []
  overload: System.NotFiniteNumberException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.NotFiniteNumberException.#ctor(System.Double)
  id: '#ctor(System.Double)'
  parent: System.NotFiniteNumberException
  langs:
  - csharp
  name: NotFiniteNumberException(Double)
  nameWithType: NotFiniteNumberException.NotFiniteNumberException(Double)
  fullName: System.NotFiniteNumberException.NotFiniteNumberException(Double)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "初始化的新实例<xref href=&quot;System.NotFiniteNumberException&quot;></xref>与无效数量的类。"
  remarks: "`offendingNumber`参数必须同时是<xref:System.Double>和数无效。</xref:System.Double>       下表显示<xref:System.NotFiniteNumberException>.</xref:System.NotFiniteNumberException>实例的初始属性的值      |属性 |值 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|空引用 (`Nothing`在 Visual Basic 中)。 |  |<xref:System.NotFiniteNumberException.OffendingNumber%2A>|无效的编号。 |</xref:System.NotFiniteNumberException.OffendingNumber%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public NotFiniteNumberException (double offendingNumber);
    parameters:
    - id: offendingNumber
      type: System.Double
      description: "导致异常的自变量的值。"
  overload: System.NotFiniteNumberException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.NotFiniteNumberException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.NotFiniteNumberException
  langs:
  - csharp
  name: NotFiniteNumberException(String)
  nameWithType: NotFiniteNumberException.NotFiniteNumberException(String)
  fullName: System.NotFiniteNumberException.NotFiniteNumberException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "初始化的新实例<xref href=&quot;System.NotFiniteNumberException&quot;></xref>与指定的错误消息的类。"
  remarks: "确保`message`字符串是可以理解的用户，并且它已本地化为当前区域性。       下表显示<xref:System.NotFiniteNumberException>.</xref:System.NotFiniteNumberException>实例的初始属性的值      |属性 |值 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|空引用 (`Nothing`在 Visual Basic 中)。 |  |<xref:System.Exception.Message%2A>|错误消息字符串。 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public NotFiniteNumberException (string message);
    parameters:
    - id: message
      type: System.String
      description: "描述错误的消息。"
  overload: System.NotFiniteNumberException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.NotFiniteNumberException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.NotFiniteNumberException
  langs:
  - csharp
  name: NotFiniteNumberException(SerializationInfo,StreamingContext)
  nameWithType: NotFiniteNumberException.NotFiniteNumberException(SerializationInfo,StreamingContext)
  fullName: System.NotFiniteNumberException.NotFiniteNumberException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "初始化的新实例<xref href=&quot;System.NotFiniteNumberException&quot;></xref>用序列化数据的类。"
  remarks: "在反序列化，以便重建通过流传输的异常对象过程中调用此构造函数。"
  syntax:
    content: protected NotFiniteNumberException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "承载序列化的对象数据的对象。"
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "有关源或目标的上下文信息。"
  overload: System.NotFiniteNumberException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.NotFiniteNumberException.#ctor(System.String,System.Double)
  id: '#ctor(System.String,System.Double)'
  parent: System.NotFiniteNumberException
  langs:
  - csharp
  name: NotFiniteNumberException(String,Double)
  nameWithType: NotFiniteNumberException.NotFiniteNumberException(String,Double)
  fullName: System.NotFiniteNumberException.NotFiniteNumberException(String,Double)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "初始化的新实例<xref href=&quot;System.NotFiniteNumberException&quot;></xref>使用指定的错误消息和数量无效的类。"
  remarks: "确保`message`字符串是可以理解的用户，并且它已本地化为当前区域性。       下表显示<xref:System.NotFiniteNumberException>.</xref:System.NotFiniteNumberException>实例的初始属性的值      |属性 |值 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|空引用 (`Nothing`在 Visual Basic 中)。 |  |<xref:System.Exception.Message%2A>|错误消息字符串。 |  |<xref:System.NotFiniteNumberException.OffendingNumber%2A>|无效的编号。 |</xref:System.NotFiniteNumberException.OffendingNumber%2A> </xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public NotFiniteNumberException (string message, double offendingNumber);
    parameters:
    - id: message
      type: System.String
      description: "描述错误的消息。"
    - id: offendingNumber
      type: System.Double
      description: "导致异常的自变量的值。"
  overload: System.NotFiniteNumberException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.NotFiniteNumberException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.NotFiniteNumberException
  langs:
  - csharp
  name: NotFiniteNumberException(String,Exception)
  nameWithType: NotFiniteNumberException.NotFiniteNumberException(String,Exception)
  fullName: System.NotFiniteNumberException.NotFiniteNumberException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "初始化的新实例<xref href=&quot;System.NotFiniteNumberException&quot;></xref>使用指定的错误消息和对内部异常的是此异常的根本原因的引用的类。"
  remarks: "前一个异常的直接结果可以包含的引用中的前一个异常引发的异常，<xref:System.Exception.InnerException%2A>属性。</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>属性返回相同的值传递到构造函数中，或`null`如果<xref:System.Exception.InnerException%2A>属性不会提供给构造函数的内部异常值。</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       下表显示<xref:System.NotFiniteNumberException>.</xref:System.NotFiniteNumberException>实例的初始属性的值      |属性 |值 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|内部异常引用。 |  |<xref:System.Exception.Message%2A>|错误消息字符串。 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public NotFiniteNumberException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "解释异常原因的错误消息。"
    - id: innerException
      type: System.Exception
      description: "导致当前异常的异常。 如果`innerException`参数不是 null 引用 (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref>在 Visual Basic 中) 中, 引发当前异常<xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;></xref>处理内部异常的块。"
  overload: System.NotFiniteNumberException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.NotFiniteNumberException.#ctor(System.String,System.Double,System.Exception)
  id: '#ctor(System.String,System.Double,System.Exception)'
  parent: System.NotFiniteNumberException
  langs:
  - csharp
  name: NotFiniteNumberException(String,Double,Exception)
  nameWithType: NotFiniteNumberException.NotFiniteNumberException(String,Double,Exception)
  fullName: System.NotFiniteNumberException.NotFiniteNumberException(String,Double,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "初始化的新实例<xref href=&quot;System.NotFiniteNumberException&quot;></xref>类指定的错误消息、 无效的数字，与此异常的根本原因的内部异常的引用。"
  remarks: "前一个异常的直接结果可以包含的引用中的前一个异常引发的异常，<xref:System.Exception.InnerException%2A>属性。</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>属性返回相同的值传递到构造函数中，或`null`如果<xref:System.Exception.InnerException%2A>属性不会提供给构造函数的内部异常值。</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       下表显示<xref:System.NotFiniteNumberException>.</xref:System.NotFiniteNumberException>实例的初始属性的值      |属性 |值 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|内部异常引用。 |  |<xref:System.Exception.Message%2A>|错误消息字符串。 |  |<xref:System.NotFiniteNumberException.OffendingNumber%2A>|无效的编号。 |</xref:System.NotFiniteNumberException.OffendingNumber%2A> </xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public NotFiniteNumberException (string message, double offendingNumber, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "解释异常原因的错误消息。"
    - id: offendingNumber
      type: System.Double
      description: "导致异常的自变量的值。"
    - id: innerException
      type: System.Exception
      description: "导致当前异常的异常。 如果`innerException`参数不是 null 引用 (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref>在 Visual Basic 中) 中, 引发当前异常<xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;></xref>处理内部异常的块。"
  overload: System.NotFiniteNumberException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.NotFiniteNumberException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.NotFiniteNumberException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: NotFiniteNumberException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.NotFiniteNumberException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - mscorlib
  namespace: System
  summary: "集<xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;></xref>与无效数量和附加异常信息的对象。"
  remarks: "<xref:System.TypeLoadException.GetObjectData%2A>设置<xref:System.Runtime.Serialization.SerializationInfo>用针对于序列化的所有异常对象数据。</xref:System.Runtime.Serialization.SerializationInfo></xref:System.TypeLoadException.GetObjectData%2A> 在反序列化期间的异常对象重建从<xref:System.Runtime.Serialization.SerializationInfo>通过流传输。</xref:System.Runtime.Serialization.SerializationInfo>       有关详细信息，请参阅<xref:System.Runtime.Serialization.SerializationInfo>。</xref:System.Runtime.Serialization.SerializationInfo>"
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "承载序列化的对象数据的对象。"
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "有关源或目标的上下文信息。"
  overload: System.NotFiniteNumberException.GetObjectData*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "The <code>info</code> object is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.NotFiniteNumberException.OffendingNumber
  id: OffendingNumber
  parent: System.NotFiniteNumberException
  langs:
  - csharp
  name: OffendingNumber
  nameWithType: NotFiniteNumberException.OffendingNumber
  fullName: System.NotFiniteNumberException.OffendingNumber
  type: Property
  assemblies:
  - mscorlib
  namespace: System
  summary: "获取为正无穷大、 负无穷大或非数值 (NaN) 的数量无效。"
  remarks: "与如果没有提供任何值传递到构造函数中或为零，OffendingNumber 属性将返回相同的值。 重写 OffendingNumber 属性，以自定义的内容或无效的值的格式。       此属性是只读的。"
  syntax:
    content: public double OffendingNumber { get; }
    return:
      type: System.Double
      description: "无效的数字。"
  overload: System.NotFiniteNumberException.OffendingNumber*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ArithmeticException
  isExternal: false
  name: System.ArithmeticException
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.NotFiniteNumberException.#ctor
  parent: System.NotFiniteNumberException
  isExternal: false
  name: NotFiniteNumberException()
  nameWithType: NotFiniteNumberException.NotFiniteNumberException()
  fullName: System.NotFiniteNumberException.NotFiniteNumberException()
- uid: System.NotFiniteNumberException.#ctor(System.Double)
  parent: System.NotFiniteNumberException
  isExternal: false
  name: NotFiniteNumberException(Double)
  nameWithType: NotFiniteNumberException.NotFiniteNumberException(Double)
  fullName: System.NotFiniteNumberException.NotFiniteNumberException(Double)
- uid: System.Double
  parent: System
  isExternal: true
  name: Double
  nameWithType: Double
  fullName: System.Double
- uid: System.NotFiniteNumberException.#ctor(System.String)
  parent: System.NotFiniteNumberException
  isExternal: false
  name: NotFiniteNumberException(String)
  nameWithType: NotFiniteNumberException.NotFiniteNumberException(String)
  fullName: System.NotFiniteNumberException.NotFiniteNumberException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.NotFiniteNumberException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.NotFiniteNumberException
  isExternal: false
  name: NotFiniteNumberException(SerializationInfo,StreamingContext)
  nameWithType: NotFiniteNumberException.NotFiniteNumberException(SerializationInfo,StreamingContext)
  fullName: System.NotFiniteNumberException.NotFiniteNumberException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.NotFiniteNumberException.#ctor(System.String,System.Double)
  parent: System.NotFiniteNumberException
  isExternal: false
  name: NotFiniteNumberException(String,Double)
  nameWithType: NotFiniteNumberException.NotFiniteNumberException(String,Double)
  fullName: System.NotFiniteNumberException.NotFiniteNumberException(String,Double)
- uid: System.NotFiniteNumberException.#ctor(System.String,System.Exception)
  parent: System.NotFiniteNumberException
  isExternal: false
  name: NotFiniteNumberException(String,Exception)
  nameWithType: NotFiniteNumberException.NotFiniteNumberException(String,Exception)
  fullName: System.NotFiniteNumberException.NotFiniteNumberException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.NotFiniteNumberException.#ctor(System.String,System.Double,System.Exception)
  parent: System.NotFiniteNumberException
  isExternal: false
  name: NotFiniteNumberException(String,Double,Exception)
  nameWithType: NotFiniteNumberException.NotFiniteNumberException(String,Double,Exception)
  fullName: System.NotFiniteNumberException.NotFiniteNumberException(String,Double,Exception)
- uid: System.NotFiniteNumberException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.NotFiniteNumberException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: NotFiniteNumberException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.NotFiniteNumberException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.NotFiniteNumberException.OffendingNumber
  parent: System.NotFiniteNumberException
  isExternal: false
  name: OffendingNumber
  nameWithType: NotFiniteNumberException.OffendingNumber
  fullName: System.NotFiniteNumberException.OffendingNumber
- uid: System.NotFiniteNumberException.#ctor*
  parent: System.NotFiniteNumberException
  isExternal: false
  name: NotFiniteNumberException
  nameWithType: NotFiniteNumberException.NotFiniteNumberException
- uid: System.NotFiniteNumberException.GetObjectData*
  parent: System.NotFiniteNumberException
  isExternal: false
  name: GetObjectData
  nameWithType: NotFiniteNumberException.GetObjectData
- uid: System.NotFiniteNumberException.OffendingNumber*
  parent: System.NotFiniteNumberException
  isExternal: false
  name: OffendingNumber
  nameWithType: NotFiniteNumberException.OffendingNumber
