### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlInternalException
  id: XamlInternalException
  children:
  - System.Xaml.XamlInternalException.#ctor
  - System.Xaml.XamlInternalException.#ctor(System.String)
  - System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: XamlInternalException
  nameWithType: XamlInternalException
  fullName: System.Xaml.XamlInternalException
  type: Class
  summary: "对于在 XAML 读取和 XAML 编写的过程中发生的内部不一致，将引发异常。"
  remarks: "仅在 XAML 读取器或 XAML 编写器系统的某些方面已扩展你的代码，且不一致情况或实现问题发生传递给.NET Framework XAML 服务的系统代码时，就会引发此异常。 从第三方，如分析 XAML 和遇到错误在 XAML 中，可能出现的异常不应引发 XamlInternalException，并应改为引发其他异常，如<xref:System.Xaml.XamlParseException>或<xref:System.Xaml.XamlObjectWriterException>.</xref:System.Xaml.XamlObjectWriterException> </xref:System.Xaml.XamlParseException>       如果你正在编写扩展.NET Framework XAML 服务的代码，具体而言，如果你编写的 XAML 读取器或 XAML 编写器实现的代码应保持此区分 XamlInternalException 和其他与 XAML 相关的异常。 你的代码仅应在其中进一步扩展你的类违反了你可调用的代码定义一些设计原则或实现模式的情况下引发 XamlInternalException。 你的代码应引发异常情况下，XAML 读取器或 XAML 编写器实现是不与扩展结合使用，用于加载第三方 XAML、 第三方 XAML 架构上下文，等其他特定于 XAML 的异常。"
  syntax:
    content: 'public class XamlInternalException : System.Xaml.XamlException'
  inheritance:
  - System.Exception
  - System.Xaml.XamlException
  implements: []
  inheritedMembers:
  - System.Xaml.XamlException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Xaml.XamlException.LineNumber
  - System.Xaml.XamlException.LinePosition
  - System.Xaml.XamlException.Message
  platform:
  - net462
- uid: System.Xaml.XamlInternalException.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlInternalException
  langs:
  - csharp
  name: XamlInternalException()
  nameWithType: XamlInternalException.XamlInternalException()
  fullName: System.Xaml.XamlInternalException.XamlInternalException()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "初始化的新实例<xref href=&quot;System.Xaml.XamlInternalException&quot;></xref>使用系统提供的描述错误的消息的类。"
  syntax:
    content: public XamlInternalException ();
    parameters: []
  overload: System.Xaml.XamlInternalException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlInternalException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Xaml.XamlInternalException
  langs:
  - csharp
  name: XamlInternalException(String)
  nameWithType: XamlInternalException.XamlInternalException(String)
  fullName: System.Xaml.XamlInternalException.XamlInternalException(String)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "初始化的新实例<xref href=&quot;System.Xaml.XamlInternalException&quot;></xref>使用指定的描述错误的消息的类。"
  syntax:
    content: public XamlInternalException (string message);
    parameters:
    - id: message
      type: System.String
      description: "描述异常的消息。"
  overload: System.Xaml.XamlInternalException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Xaml.XamlInternalException
  langs:
  - csharp
  name: XamlInternalException(SerializationInfo,StreamingContext)
  nameWithType: XamlInternalException.XamlInternalException(SerializationInfo,StreamingContext)
  fullName: System.Xaml.XamlInternalException.XamlInternalException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "初始化的新实例<xref href=&quot;System.Xaml.XamlInternalException&quot;></xref>用序列化数据的类。"
  syntax:
    content: protected XamlInternalException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "承载序列化的对象数据的对象。"
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "有关源或目标的上下文信息。"
  overload: System.Xaml.XamlInternalException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Xaml.XamlInternalException
  langs:
  - csharp
  name: XamlInternalException(String,Exception)
  nameWithType: XamlInternalException.XamlInternalException(String,Exception)
  fullName: System.Xaml.XamlInternalException.XamlInternalException(String,Exception)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "初始化的新实例<xref href=&quot;System.Xaml.XamlInternalException&quot;></xref>使用指定的错误消息和对导致此异常的内部异常的引用的类。"
  syntax:
    content: public XamlInternalException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "描述异常的消息。"
    - id: innerException
      type: System.Exception
      description: "导致当前异常的异常。 如果`innerException`参数不是<xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>中, 引发当前异常<xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;></xref>处理内部异常的块。"
  overload: System.Xaml.XamlInternalException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Xaml.XamlException
  isExternal: false
  name: System.Xaml.XamlException
- uid: System.Xaml.XamlInternalException.#ctor
  parent: System.Xaml.XamlInternalException
  isExternal: false
  name: XamlInternalException()
  nameWithType: XamlInternalException.XamlInternalException()
  fullName: System.Xaml.XamlInternalException.XamlInternalException()
- uid: System.Xaml.XamlInternalException.#ctor(System.String)
  parent: System.Xaml.XamlInternalException
  isExternal: false
  name: XamlInternalException(String)
  nameWithType: XamlInternalException.XamlInternalException(String)
  fullName: System.Xaml.XamlInternalException.XamlInternalException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Xaml.XamlInternalException
  isExternal: false
  name: XamlInternalException(SerializationInfo,StreamingContext)
  nameWithType: XamlInternalException.XamlInternalException(SerializationInfo,StreamingContext)
  fullName: System.Xaml.XamlInternalException.XamlInternalException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)
  parent: System.Xaml.XamlInternalException
  isExternal: false
  name: XamlInternalException(String,Exception)
  nameWithType: XamlInternalException.XamlInternalException(String,Exception)
  fullName: System.Xaml.XamlInternalException.XamlInternalException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Xaml.XamlInternalException.#ctor*
  parent: System.Xaml.XamlInternalException
  isExternal: false
  name: XamlInternalException
  nameWithType: XamlInternalException.XamlInternalException
